version: "3.7"
services:
  api:
    image: piotras/projectx:latest
    build:
      args:
        - PORT=8090
      dockerfile: Dockerfile
      context: .
    environment:
      - PROJECTX_CASSANDRA_HOST=cassandra-node1
      - PROJECTX_CASSANDRA_USER=projectx
      - PROJECTX_CASSANDRA_PASSWORD=projectx
      - PROJECTX_CASSANDRA_KEYSPACE=projectx
    ports:
      - "8090:8090"
    command: ["server", "--port=8090"]
  test:
    image: alpine:3.11.6