version: "3.7"
services:
  cassandra-node1:
    image: bitnami/cassandra:3.11.6
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=projectx
      - CASSANDRA_USER=projectx
    restart: always
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./var/lib/cassandra:/var/lib/cassandra
  cassandra-load-keyspace:
    image: bitnami/cassandra:3.11.6
    depends_on:
      - cassandra-node1
    volumes:
      - ./cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra-node1 -u projectx -p projectx -f /schema.cql"